/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 46978cd49fdef4a6fffcf08c6d5460bb)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	MCP_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
